In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC 
from sklearn.ensemble import RandomForestClassifier

import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()

In [2]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

In [3]:
lr = LogisticRegression()
lr.fit(x_train, y_train)
lr.score(x_test, y_test)

D:\ML\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:470: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9555555555555556

In [4]:
svm = SVC()
svm.fit(x_train, y_train)
svm.score(x_test, y_test)

0.9851851851851852

In [5]:
rd = RandomForestClassifier()
rd.fit(x_train, y_train)
rd.score(x_test, y_test)

0.9722222222222222

In [6]:
from sklearn.model_selection import KFold

kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [7]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [8]:
def get_score(model, x_train, x_test, y_train, y_test):
    model.fit(x_train, y_train)
    return model.score(x_test, y_test)

In [9]:
from sklearn.model_selection import StratifiedKFold
n_splits=3
folds = StratifiedKFold(n_splits)

In [10]:
# Useless -> do not need to write 

scores_l = []
scores_svm = []
scores_rf = []


for train_index, test_index in kf.split(digits.data):
    x_train, x_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index],  digits.target[test_index]

    scores_l.append(get_score(LogisticRegression(max_iter=1000), x_train, x_test, y_train, y_test))
    scores_svm.append(get_score(SVC(), x_train, x_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), x_train, x_test, y_train, y_test))
    

In [11]:
scores_l

[0.9248747913188647, 0.9432387312186978, 0.9148580968280468]

In [12]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [13]:
scores_rf

[0.9315525876460768, 0.9382303839732888, 0.9215358931552587]

In [14]:
from sklearn.model_selection import cross_val_score

In [15]:
cross_val_score(LogisticRegression(max_iter=1000), digits.data, digits.target)

array([0.92222222, 0.86944444, 0.94150418, 0.94150418, 0.89693593])

In [16]:
cross_val_score(SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [17]:
cross_val_score(RandomForestClassifier(n_estimators = 40), digits.data, digits.target)

array([0.93333333, 0.89722222, 0.94150418, 0.94986072, 0.91086351])